### ISSUE TITLE
php的马

### ISSUE THREAD

**Issue by Imtinmin** [yzddmr6/php_xor_bypass#3]
为什么php必须要一个字母

**Comment by yzddmr6** [comment]
麻烦提issue之前学习一下php语言基本语法以及一句话的原理

**Comment by Imtinmin** [comment]
为什么不能两个不可见字符生成webshell，例如"\x81"^"\xe0" = ‘a’

**Comment by yzddmr6** [comment]
可以啊
我在蚁剑插件版里就是两个十六进制异或
这里的脚本懒得改了，原理是一样的

**Comment by Imtinmin** [comment]
噢噢，谢谢师傅。蚁剑那个不知道怎么用……



------------------ 原始邮件 ------------------
发件人: "Mr6"<notifications@github.com>; 
发送时间: 2019年7月27日(星期六) 下午2:53
收件人: "yzddmr6/webshell-venom"<webshell-venom@noreply.github.com>; 
抄送: "954093370"<954093370@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yzddmr6/webshell-venom] php的马 (#3)




可以啊
 我在蚁剑插件版里就是两个十六进制异或
 这里的脚本懒得改了，原理是一样的

**Comment by yzddmr6** [comment]
为什么不知道怎么用。。。
ctrl c ctrl v

**Comment by Imtinmin** [comment]
emmm,不是插件吗，以为要安装




------------------ 原始邮件 ------------------
发件人: "Mr6"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 下午2:58
收件人: "yzddmr6/webshell-venom"<webshell-venom@noreply.github.com>;
抄送: "954093370"<954093370@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yzddmr6/webshell-venom] php的马 (#3)




为什么不知道怎么用。。。
 ctrl c ctrl v
