### ISSUE TITLE
php的免杀又夭折了....

### ISSUE THREAD

**Issue by handbye** [yzddmr6/php_xor_bypass#4]
![image](https://user-images.githubusercontent.com/26617058/72677768-0edf8580-3adb-11ea-88c3-e62ecb6f3843.png)

**Comment by yzddmr6** [comment]
重要的是思路不是现成的shell
参考[这篇文章](https://www.anquanke.com/post/id/193042)自己改一下吧

**Comment by handbye** [comment]
谢谢，使用这个思路可以免杀
